### PR TITLE
Added `react` and `react-dom` to  Peer dependencies

### PR DESCRIPTION
**Pull request by ateev**
Why ?

https://nodejs.org/en/blog/npm/peer-dependencies/

### CODE REVIEW

**Comment by rrutsche** [comment]
Did it!

**Comment by ateev** [comment]
@RRutsche publish it ?

**Comment by rrutsche** [comment]
@ateev [Version 1.2.0](https://www.npmjs.com/package/react-parallax) is already published on npm

**Comment by ateev** [comment]
@RRutsche Oh sorry ! I was checking in [Releases](https://github.com/RRutsche/react-parallax/releases) section. Thanks for such quick reply !

**Comment by rrutsche** [comment]
@ateev Yeah, I forgot to push the new tag to origin. But npm is up-to-date.

**Pull request merged**
