### PR TITLE
added bgImageSrcSet prop

### PR DESCRIPTION
**Pull request by carterchung**
Feel free to decline and do it your own way (naming conventions, etc.), of course -- but here's what I've tested to work in my own app for reference

### CODE REVIEW

**Comment by rrutsche** [comment]
Thanks for the pull request. I never worked with `srcset` before. I just read that it is often used in combination with `sizes`. Does it make sense to also add this attribute?

**Comment by alx-xo** [comment]
Adding a `sizes` attribute would be ideal

**Comment by rrutsche** [comment]
@carterchung 
I merged your pull request and also added the new prop to the state update in `loadImage` and did the same for `bgImageSizes` attribute.  I hope this is working for you now. Feel free to write me if there is something missing.

regards

**Comment by carterchung** [comment]
Awesome, thanks @RRutsche!

**Pull request merged**
